#!/usr/bin/env bash

config="/etc/rpi-fan-control/rpi-fan-control.conf"
. "$config"

function get_cpu_temp {
  /opt/vc/bin/vcgencmd measure_temp | grep -Eo "[0-9]*\." | sed 's/\.//g'
}

function set_pin {
  pin=$1
  value=$2

  echo "$value" > "/sys/class/gpio/gpio${pin}/value"
}

# Initialize pin
if [[ ! -e "/sys/class/gpio/gpio${fan_pin}" ]]; then
    echo "$fan_pin" > /sys/class/gpio/export
fi
echo "out" > "/sys/class/gpio/gpio${fan_pin}/direction"

while : ; do
  temp=$(get_cpu_temp)

  if [[ "$temp" -ge "$temp_high" ]] && [[ ! "$cooling" ]]; then
    # Turn on fan
    set_pin "$fan_pin" 1
    cooling="true"
  fi

  if [[ "$temp" -lt "$temp_low" ]] && [[ "$cooling" ]]; then
    # Turn off fan
    set_pin "$fan_pin" 0
    unset cooling
  fi

  sleep "$check_delay"
done
