#!/bin/sh

### BEGIN INIT INFO
# Provides:          rpi-fan-control
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

. /lib/lsb/init-functions
NAME="rpi-fan-control"
EXEC="/usr/sbin/$NAME"
PID_FILE="/var/run/$NAME.pid"

case "$1" in
start)
	echo -n "Starting $NAME... "

	if [ -e $PID_FILE ]; then
		echo "already running!"
		exit 0
	fi

	echo "---------------------" >> $LOG
	$EXEC &

	PID="$!"
	echo $PID > $PID_FILE

	echo "done! PID=$PID"
;;

stop)
	echo -n "Stopping $NAME... "

	if [ ! -e $PID_FILE ]; then
		echo "nothing to stop!"
		exit 0
	fi

	PID=`cat $PID_FILE`
	kill $PID
	rm $PID_FILE

	echo "done! PID=$PID"
;;

restart)
	$0 stop
	$0 start
;;

force-reload)
	$0 restart
;;

status)
	if [ -e $PID_FILE ]; then
		echo "$NAME is running"
		exit 0
	else
		echo "$NAME is not running"
		exit 1
	fi
;;

*)
	echo "Usage: $NAME {start|stop|restart|status|force-reload}"
	exit 1
esac
